# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'Encuentros'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: 'G-BZHCWQ0GPM'

menu:
- {name: 'Interesting Facts', folder: 'pages', file: 'facts.html'}
- {name: 'Learning Resources', folder: 'pages', file: 'resources.html'}
- {name: 'Sample Posts', folder: 'pages', file: 'sample-posts.html'}
- {name: 'Documentation', folder: 'pages', file: 'documentation.html'}
- {name: 'About', folder: 'pages', file: 'about.html'}
- {name: 'Contact', folder: 'pages', file: 'contact.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
# - {icon: 'twitter', link: 'https://twitter.com/paululele'}
- {icon: 'facebook', link: 'https://www.facebook.com/francoleonel.marsico'}
- {icon: 'instagram', link: 'https://instagram.com/fran_marsico'}
- {icon: 'envelope', link: 'mailto: franco.lmarsico@gmail.com'}
- {icon: 'github', link: 'https://github.com/MarsicoFL/'}
- {icon: 'rss-square', link: 'http://www.ic.fcen.uba.ar/actividades-academicas/transferencia/redes-complejas'}

# Customize site text
#pagination:
#  next_page: 'Newer'
#  previous_page: 'Older'

sharing_button_prompt: 'Compartir'

related_posts: 'Posteos relacionados...'

post_date_prefix: 'Publicado el'
