# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'Encuentros'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: 'G-BZHCWQ0GPM'

menu:
- {name: 'Divulgación', folder: 'pages', file: 'Divulgacion.html'}
- {name: 'Tecnologías de información', folder: 'pages', file: 'Monitoreo_TDF.html'}
- {name: 'Genética Estadística', folder: 'pages', file: 'Tutoriales.html'}
- {name: 'Autor', folder: 'pages', file: 'Autor.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
# - {icon: 'twitter', link: 'https://twitter.com/paululele'}
# - {icon: 'facebook', link: 'https://www.facebook.com/francoleonel.marsico'}
# - {icon: 'instagram', link: 'https://instagram.com/fran_marsico'}
- {icon: 'envelope', link: 'mailto: franco.lmarsico@gmail.com'}
- {icon: 'github', link: 'https://github.com/MarsicoFL/'}
- {icon: 'flask', link: 'http://www.ic.fcen.uba.ar/redescomplejas/index.html'}

# Customize site text
#pagination:
#  next_page: 'Newer'
#  previous_page: 'Older'

sharing_button_prompt: 'Compartir'

related_posts: 'Posteos relacionados...'

post_date_prefix: 'Publicado el'
